\c biblestudy;
TRUNCATE TABLE material.Book CASCADE;

SELECT popOldTstBooks('Genesis');
SELECT popOldTstBooks('Exodus');
SELECT popOldTstBooks('Leviticus');
SELECT popOldTstBooks('Numbers');
SELECT popOldTstBooks('Deuteronomy');
SELECT popOldTstBooks('Joshua');
SELECT popOldTstBooks('Judges');
SELECT popOldTstBooks('Ruth');
SELECT popOldTstBooks('1 Samuel');
SELECT popOldTstBooks('2 Samuel');
SELECT popOldTstBooks('1 Kings');
SELECT popOldTstBooks('2 Kings');
SELECT popOldTstBooks('1 Chronicles');
SELECT popOldTstBooks('2 Chronicles');
SELECT popOldTstBooks('Ezra');
SELECT popOldTstBooks('Nehemiah');
SELECT popOldTstBooks('Esther');
SELECT popOldTstBooks('Job');
SELECT popOldTstBooks('Psalms');
SELECT popOldTstBooks('Proverbs');
SELECT popOldTstBooks('Ecclesiastes');
SELECT popOldTstBooks('Song of Songs');
SELECT popOldTstBooks('Isaiah');
SELECT popOldTstBooks('Jeremiah');
SELECT popOldTstBooks('Lamentations');
SELECT popOldTstBooks('Ezekiel');
SELECT popOldTstBooks('Daniel');
SELECT popOldTstBooks('Hosea');
SELECT popOldTstBooks('Joel');
SELECT popOldTstBooks('Amos');
SELECT popOldTstBooks('Obadiah');
SELECT popOldTstBooks('Jonah');
SELECT popOldTstBooks('Micah');
SELECT popOldTstBooks('Nahum');
SELECT popOldTstBooks('Habakkuk');
SELECT popOldTstBooks('Zephaniah');
SELECT popOldTstBooks('Haggai');
SELECT popOldTstBooks('Zechariah');
SELECT popOldTstBooks('Malachi');


SELECT popNewTstBooks('Mathew');
SELECT popNewTstBooks('Mark');
SELECT popNewTstBooks('Luke');
SELECT popNewTstBooks('John');
SELECT popNewTstBooks('Acts');
SELECT popNewTstBooks('Romans');
SELECT popNewTstBooks('1 Corinthians');
SELECT popNewTstBooks('2 Corinthians');
SELECT popNewTstBooks('Galatians');
SELECT popNewTstBooks('Ephesians');
SELECT popNewTstBooks('Philippians');
SELECT popNewTstBooks('Colossians');
SELECT popNewTstBooks('1 Thessalonians');
SELECT popNewTstBooks('2 Thessalonians');
SELECT popNewTstBooks('1 Timothy');
SELECT popNewTstBooks('2 Timothy');
SELECT popNewTstBooks('Titus');
SELECT popNewTstBooks('Philemon');
SELECT popNewTstBooks('Hebrews');
SELECT popNewTstBooks('James');
SELECT popNewTstBooks('1 Peter');
SELECT popNewTstBooks('2 Peter');
SELECT popNewTstBooks('1 John');
SELECT popNewTstBooks('2 John');
SELECT popNewTstBooks('3 John');
SELECT popNewTstBooks('Jude');
SELECT popNewTstBooks('Revelation');
